# Generated by Django 5.2 on 2025-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementstaff',
            options={'permissions': [('full_access', 'Full Access'), ('add_doctor', 'Add Doctor'), ('add_patient', 'Add Patient'), ('assign_doctor', 'Assign Doctor')]},
        ),
        migrations.AlterField(
            model_name='managementstaff',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='staff_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='managementstaff',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='staff_permissions', to='auth.permission'),
        ),
    ]
