# Generated by Django 5.2 on 2025-05-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_managementstaff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.PositiveSmallIntegerField(choices=[('0', 'Male'), ('1', 'Female')])),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('full_access', 'Full Access'), ('add_doctor', 'Add Doctor'), ('add_patient', 'Add Patient'), ('assign_doctor', 'Assign Doctor')],
            },
        ),
        migrations.AlterModelOptions(
            name='managementstaff',
            options={},
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.person')),
                ('specialization', models.CharField(max_length=100)),
            ],
            bases=('api.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.person')),
                ('medical_history', models.TextField()),
                ('assigned_doctor', models.ManyToManyField(related_name='patients', to='api.doctor')),
            ],
            bases=('api.person',),
        ),
    ]
