# Generated by Django 5.2 on 2025-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_alter_managementstaff_options_doctor_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('full_access', 'Full Access'), ('assign_doctor', 'Assign Doctor')]},
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
    ]
